# This workflow will build a Java project with Maven and run tests

name: Version input

on: workflow_dispatch

env:
  DEFAULT_VERSION: ''

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Get default version
        id: retrieve_pom_version
        run: |
          echo "VERSION=1.2.3" >> "$GITHUB_OUTPUT"
      - name: Print pom_version
        env:
          DEFAULT_VERSION = ${{steps.retrieve_pom_version.outputs.VERSION}}
        run: echo "The version in POM is $DEFAULT_VERSION"
